apiVersion: deploy.hybridapp.io/v1alpha1
kind: Operator
metadata:
  name: hybridapp
spec:
  replicas: 1
  license:
    accept: true
  core:
    deployable:
      enabled: true
    placement:
      enabled: true
  tools:
    assembler:
      enabled: true
