apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "deploy.hybridapp.io/v1alpha1",
          "kind": "Operator",
          "metadata": {
            "name": "hybrid-application-model"
          },
          "spec": {
            "core": {
              "deployable": {
                "enabled": true
              },
              "placement": {
                "enabled": false
              }
            },
            "license": {
              "accept": true
            },
            "replicas": 1,
            "tools": {
              "assembler": {
                "enabled": true
              }
            }
          }
        }
      ]
    capabilities: Basic Install
  name: ham-deploy.v0.2.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Operator is the Schema for the operators API
      kind: Operator
      name: operators.deploy.hybridapp.io
      version: v1alpha1
  displayName: Ham Deploy
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - deploy.hybridapp.io
          resources:
          - operators
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - create
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - watch
        serviceAccountName: ham-deploy
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: hybrid-application-model
      deployments:
      - name: ham-deploy
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ham-deploy
          strategy: {}
          template:
            metadata:
              labels:
                name: ham-deploy
            spec:
              containers:
              - command:
                - ham-deploy
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ham-deploy
                image: quay.io/hybridappio/ham-deploy:latest
                imagePullPolicy: Always
                name: ham-deploy
                resources: {}
              serviceAccountName: ham-deploy
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - configmaps
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ham-deploy
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  replaces: ham-deploy.v0.1.0
  version: 0.2.0
