kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ham-deploy
subjects:
- kind: ServiceAccount
  namespace: default
  name: ham-deploy
roleRef:
  kind: Role
  name: ham-deploy
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ham-deploy
subjects:
- kind: ServiceAccount
  namespace: default
  name: ham-deploy
roleRef:
  kind: ClusterRole
  name: ham-deploy
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hybrid-application-model
subjects:
- kind: ServiceAccount
  namespace: default
  name: hybrid-application-model
roleRef:
  kind: ClusterRole
  name: hybrid-application-model
  apiGroup: rbac.authorization.k8s.io